// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Cooperative;

namespace Model.Cooperative.Migrations
{
    [DbContext(typeof(CooperativeContext))]
    [Migration("20230718122249_stepProjectSelectedCategorie")]
    partial class stepProjectSelectedCategorie
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Cooperative.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Model.Cooperative.Coop", b =>
                {
                    b.Property<int>("IdCoop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CoopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCoop");

                    b.ToTable("Coop");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AfterStepBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ExpenseBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ManagerSalary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("DailySalary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPersonId")
                        .HasColumnType("int");

                    b.Property<int?>("StepProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StepProjectId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.Cooperative.LivestockImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LivestockId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("LivestockId");

                    b.ToTable("LivestockImages");
                });

            modelBuilder.Entity("Model.Cooperative.Livestock", b =>
                {
                    b.Property<int>("LivestockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoopId")
                        .HasColumnType("int");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDropped")
                        .HasColumnType("datetime2");

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumFemalesPaired")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SellDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("LivestockId");

                    b.HasIndex("CoopId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Livestock");

                    b.HasDiscriminator<string>("LivestockType").HasValue("Livestock");
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GrandparentTag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("Membre");
                });

            modelBuilder.Entity("Model.Cooperative.Model.GoatPair", b =>
                {
                    b.Property<int>("GoatPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("FirstGoatLivestockId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondGoatLivestockId")
                        .HasColumnType("int");

                    b.HasKey("GoatPairId");

                    b.HasIndex("FirstGoatLivestockId");

                    b.HasIndex("SecondGoatLivestockId");

                    b.ToTable("GoatPairs");
                });

            modelBuilder.Entity("Model.Cooperative.Model.StepCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StepCategories");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("OfflineMember");
                });

            modelBuilder.Entity("Model.Cooperative.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("Model.Cooperative.PersonPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("OfflineMemberMembreId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfflineMemberMembreId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonImages");
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonth")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CoopIdCoop");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.Property<int>("StepProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NbreOfDays")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool?>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StepBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StepCategorieId")
                        .HasColumnType("int");

                    b.Property<bool>("VetVisit")
                        .HasColumnType("bit");

                    b.HasKey("StepProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StepCategorieId");

                    b.ToTable("StepProject");
                });

            modelBuilder.Entity("Model.Cooperative.StepProjectPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StepProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepProjectId");

                    b.ToTable("StepProjectPicture");
                });

            modelBuilder.Entity("Model.Cooperative.Goat", b =>
                {
                    b.HasBaseType("Model.Cooperative.Livestock");

                    b.ToTable("Livestock");

                    b.HasDiscriminator().HasValue("Goat");
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasBaseType("Model.Cooperative.Person");

                    b.Property<string>("CoopUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CoopUserId");

                    b.HasDiscriminator().HasValue("ConnectedMember");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.HasOne("Model.Cooperative.CoopManager", "Manager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Model.Cooperative.StepProject", "Step")
                        .WithMany()
                        .HasForeignKey("StepProjectId");
                });

            modelBuilder.Entity("Model.Cooperative.LivestockImage", b =>
                {
                    b.HasOne("Model.Cooperative.Livestock", "Livestock")
                        .WithMany("Images")
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Cooperative.Livestock", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "Cooperative")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Livestock", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Model.Cooperative.Livestock", "Mother")
                        .WithMany("Kids")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("Membres")
                        .HasForeignKey("MyCoopIdCoop");

                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Model.Cooperative.Model.GoatPair", b =>
                {
                    b.HasOne("Model.Cooperative.Goat", "FirstGoat")
                        .WithMany()
                        .HasForeignKey("FirstGoatLivestockId");

                    b.HasOne("Model.Cooperative.Goat", "SecondGoat")
                        .WithMany()
                        .HasForeignKey("SecondGoatLivestockId");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("OfflineMembers")
                        .HasForeignKey("MyCoopIdCoop");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Model.Cooperative.PersonPicture", b =>
                {
                    b.HasOne("Model.Cooperative.OfflineMember", null)
                        .WithMany("Images")
                        .HasForeignKey("OfflineMemberMembreId");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", null)
                        .WithMany("Projects")
                        .HasForeignKey("CoopIdCoop");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.HasOne("Model.Cooperative.Employee", "Employee")
                        .WithMany("Steps")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("Model.Cooperative.Project", "project")
                        .WithMany()
                        .HasForeignKey("ProjectId");

                    b.HasOne("Model.Cooperative.Model.StepCategorie", "StepCategorie")
                        .WithMany("StepProjects")
                        .HasForeignKey("StepCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Cooperative.StepProjectPicture", b =>
                {
                    b.HasOne("Model.Cooperative.StepProject", "StepProject")
                        .WithMany()
                        .HasForeignKey("StepProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasOne("Model.Cooperative.ApplicationUser", "CoopUser")
                        .WithMany()
                        .HasForeignKey("CoopUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
