// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Cooperative;

namespace Model.Cooperative.Migrations
{
    [DbContext(typeof(CooperativeContext))]
    [Migration("20230425185150_StepProjectDuplicateColumnFix")]
    partial class StepProjectDuplicateColumnFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Model.Cooperative.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Model.Cooperative.Coop", b =>
                {
                    b.Property<int>("IdCoop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CoopName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCoop");

                    b.ToTable("Coop");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AfterStepBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ExpenseBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ProjectId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("SelectedPersonId")
                        .HasColumnType("int");

                    b.Property<int?>("StepProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StepProjectId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("Membre");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int?>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("OfflineMember");
                });

            modelBuilder.Entity("Model.Cooperative.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonth")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CoopIdCoop");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.Property<int>("StepProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NbreOfDays")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StepBuget")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("StepProjectId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("StepProject");
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasBaseType("Model.Cooperative.Person");

                    b.Property<string>("CoopUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CoopUserId");

                    b.HasDiscriminator().HasValue("ConnectedMember");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.HasOne("Model.Cooperative.CoopManager", "Manager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("ManagerId");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.HasOne("Model.Cooperative.StepProject", "Step")
                        .WithMany()
                        .HasForeignKey("StepProjectId");
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("Membres")
                        .HasForeignKey("MyCoopIdCoop");

                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("OfflineMembers")
                        .HasForeignKey("MyCoopIdCoop");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", null)
                        .WithMany("Projects")
                        .HasForeignKey("CoopIdCoop");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.HasOne("Model.Cooperative.Employee", "Employee")
                        .WithMany("Steps")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasOne("Model.Cooperative.ApplicationUser", "CoopUser")
                        .WithMany()
                        .HasForeignKey("CoopUserId");
                });
#pragma warning restore 612, 618
        }
    }
}
