// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Model.Cooperative;

#nullable disable

namespace Model.Cooperative.Migrations
{
    [DbContext(typeof(CooperativeContext))]
    partial class CooperativeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Model.Cooperative.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("Fees")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("Model.Cooperative.Coop", b =>
                {
                    b.Property<int>("IdCoop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCoop"));

                    b.Property<decimal>("Budget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CoopName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCoop");

                    b.ToTable("Coop");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<decimal>("AfterStepBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal?>("ExpenseBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ManagerSalary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Manager");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<decimal>("DailySalary")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ManagerId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("SelectedPersonId")
                        .HasColumnType("int");

                    b.Property<int>("StepProjectId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId");

                    b.HasIndex("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("StepProjectId");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("Model.Cooperative.Livestock", b =>
                {
                    b.Property<int>("LivestockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivestockId"));

                    b.Property<double>("Age")
                        .HasColumnType("float");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoopId")
                        .HasColumnType("int");

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAlive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSold")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDropped")
                        .HasColumnType("datetime2");

                    b.Property<string>("LivestockType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumFemalesPaired")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime?>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SellDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("LivestockId");

                    b.HasIndex("CoopId");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Livestock");

                    b.HasDiscriminator<string>("LivestockType").HasValue("Livestock");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Cooperative.LivestockImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("LivestockId")
                        .HasColumnType("int");

                    b.HasKey("ImageId");

                    b.HasIndex("LivestockId");

                    b.ToTable("LivestockImages");
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembreId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("GrandparentTag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Town")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("Membre");
                });

            modelBuilder.Entity("Model.Cooperative.Model.ApplicationUserImage", b =>
                {
                    b.Property<int>("ApplicationUserImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationUserImageId"));

                    b.Property<string>("AspUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.HasKey("ApplicationUserImageId");

                    b.HasIndex("AspUserId")
                        .IsUnique();

                    b.ToTable("ApplicationUserImage");
                });

            modelBuilder.Entity("Model.Cooperative.Model.GoatPair", b =>
                {
                    b.Property<int>("GoatPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GoatPairId"));

                    b.Property<int?>("FirstGoatLivestockId")
                        .HasColumnType("int");

                    b.Property<int?>("SecondGoatLivestockId")
                        .HasColumnType("int");

                    b.HasKey("GoatPairId");

                    b.HasIndex("FirstGoatLivestockId");

                    b.HasIndex("SecondGoatLivestockId");

                    b.ToTable("GoatPairs");
                });

            modelBuilder.Entity("Model.Cooperative.Model.SocialAssistance", b =>
                {
                    b.Property<int>("SocialAssistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialAssistId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("DateReceived")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRepaid")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateValidated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRepaid")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRepayable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("bit");

                    b.Property<int>("MembreId")
                        .HasColumnType("int");

                    b.HasKey("SocialAssistId");

                    b.HasIndex("MembreId")
                        .IsUnique()
                        .HasFilter("[IsRepaid] = 0");

                    b.ToTable("SocialAssistances");
                });

            modelBuilder.Entity("Model.Cooperative.Model.StepCategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StepCategories");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.Property<int>("MembreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembreId"));

                    b.Property<decimal>("FeesPerYear")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MyCoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("MembreId");

                    b.HasIndex("MyCoopIdCoop");

                    b.HasIndex("PersonId");

                    b.ToTable("OfflineMember");
                });

            modelBuilder.Entity("Model.Cooperative.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdNumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Model.Cooperative.PersonPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("OfflineMemberMembreId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfflineMemberMembreId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonImages");
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.Property<int>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectId"));

                    b.Property<int?>("CoopIdCoop")
                        .HasColumnType("int");

                    b.Property<int>("DurationInMonth")
                        .HasColumnType("int");

                    b.Property<int>("Efficiency")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProjectBudget")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ProjectId");

                    b.HasIndex("CoopIdCoop");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.Property<int>("StepProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StepProjectId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<decimal>("NbreOfDays")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<bool?>("Reviewed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("StepBudget")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StepCategorieId")
                        .HasColumnType("int");

                    b.Property<bool>("VetVisit")
                        .HasColumnType("bit");

                    b.HasKey("StepProjectId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("StepCategorieId");

                    b.ToTable("StepProject");
                });

            modelBuilder.Entity("Model.Cooperative.StepProjectPicture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("StepProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StepProjectId");

                    b.ToTable("StepProjectPicture");
                });

            modelBuilder.Entity("Model.Cooperative.Goat", b =>
                {
                    b.HasBaseType("Model.Cooperative.Livestock");

                    b.ToTable("Livestock");

                    b.HasDiscriminator().HasValue("Goat");
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasBaseType("Model.Cooperative.Person");

                    b.Property<string>("CoopUserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasIndex("CoopUserId");

                    b.HasDiscriminator().HasValue("ConnectedMember");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.HasOne("Model.Cooperative.CoopManager", "Manager")
                        .WithMany("ManagedEmployees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.StepProject", "Step")
                        .WithMany()
                        .HasForeignKey("StepProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manager");

                    b.Navigation("Person");

                    b.Navigation("Step");
                });

            modelBuilder.Entity("Model.Cooperative.Livestock", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "Cooperative")
                        .WithMany()
                        .HasForeignKey("CoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Livestock", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Model.Cooperative.Livestock", "Mother")
                        .WithMany("Kids")
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Cooperative");

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Model.Cooperative.LivestockImage", b =>
                {
                    b.HasOne("Model.Cooperative.Livestock", "Livestock")
                        .WithMany("Images")
                        .HasForeignKey("LivestockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livestock");
                });

            modelBuilder.Entity("Model.Cooperative.Membre", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("Membres")
                        .HasForeignKey("MyCoopIdCoop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.ConnectedMember", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyCoop");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Model.Cooperative.Model.ApplicationUserImage", b =>
                {
                    b.HasOne("Model.Cooperative.ApplicationUser", "AspUser")
                        .WithOne("UserImage")
                        .HasForeignKey("Model.Cooperative.Model.ApplicationUserImage", "AspUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AspUser");
                });

            modelBuilder.Entity("Model.Cooperative.Model.GoatPair", b =>
                {
                    b.HasOne("Model.Cooperative.Goat", "FirstGoat")
                        .WithMany()
                        .HasForeignKey("FirstGoatLivestockId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Model.Cooperative.Goat", "SecondGoat")
                        .WithMany()
                        .HasForeignKey("SecondGoatLivestockId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("FirstGoat");

                    b.Navigation("SecondGoat");
                });

            modelBuilder.Entity("Model.Cooperative.Model.SocialAssistance", b =>
                {
                    b.HasOne("Model.Cooperative.Membre", "Membre")
                        .WithMany()
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", "MyCoop")
                        .WithMany("OfflineMembers")
                        .HasForeignKey("MyCoopIdCoop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MyCoop");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Model.Cooperative.PersonPicture", b =>
                {
                    b.HasOne("Model.Cooperative.OfflineMember", null)
                        .WithMany("Images")
                        .HasForeignKey("OfflineMemberMembreId");

                    b.HasOne("Model.Cooperative.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Model.Cooperative.Project", b =>
                {
                    b.HasOne("Model.Cooperative.Coop", null)
                        .WithMany("Projects")
                        .HasForeignKey("CoopIdCoop");
                });

            modelBuilder.Entity("Model.Cooperative.StepProject", b =>
                {
                    b.HasOne("Model.Cooperative.Employee", "Employee")
                        .WithMany("Steps")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Project", "project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Model.Cooperative.Model.StepCategorie", "StepCategorie")
                        .WithMany("StepProjects")
                        .HasForeignKey("StepCategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("StepCategorie");

                    b.Navigation("project");
                });

            modelBuilder.Entity("Model.Cooperative.StepProjectPicture", b =>
                {
                    b.HasOne("Model.Cooperative.StepProject", "StepProject")
                        .WithMany()
                        .HasForeignKey("StepProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StepProject");
                });

            modelBuilder.Entity("Model.Cooperative.ConnectedMember", b =>
                {
                    b.HasOne("Model.Cooperative.ApplicationUser", "CoopUser")
                        .WithMany()
                        .HasForeignKey("CoopUserId");

                    b.Navigation("CoopUser");
                });

            modelBuilder.Entity("Model.Cooperative.ApplicationUser", b =>
                {
                    b.Navigation("UserImage")
                        .IsRequired();
                });

            modelBuilder.Entity("Model.Cooperative.Coop", b =>
                {
                    b.Navigation("Membres");

                    b.Navigation("OfflineMembers");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Model.Cooperative.CoopManager", b =>
                {
                    b.Navigation("ManagedEmployees");
                });

            modelBuilder.Entity("Model.Cooperative.Employee", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("Model.Cooperative.Livestock", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Kids");
                });

            modelBuilder.Entity("Model.Cooperative.Model.StepCategorie", b =>
                {
                    b.Navigation("StepProjects");
                });

            modelBuilder.Entity("Model.Cooperative.OfflineMember", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
